
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version U-2022.12                           ***
***                      (2.7886616, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2022 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'ug142.eecg.toronto.edu' by user 'hemarath'
Binary '/CMC/tools/synopsys/sentaurus_vU-2022.12/bin/../tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 --max_threads 2 -job 38 -swb_pid 1784752 -gsub_pid 1825241 -gsub_host ug142.eecg.toronto.edu -gsub_port 42595 /nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023'
Current directory '/nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/CMC/tools/synopsys/sentaurus_vU-2022.12/bin/..
	STRELEASE=current
	STROOT_LIB=/CMC/tools/synopsys/sentaurus_vU-2022.12/bin/../tcad/current/lib
	STDB=/homes/h/hemarath/SentaurusDB
	DATEX=/CMC/tools/synopsys/sentaurus_vU-2022.12/bin/../tcad/current/lib/datexcodes.txt
	DISPLAY=localhost:21.0

Project '/nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023'
INITIALIZING PREPROCESSOR:
Application mode : traditional
Loading project tree '/nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023/gtree.dat'
Loading jobs and dependence graph '"/nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023/gexec.cmd"'
Loading project variables '/nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023/sdevice1_des.cmd
Reading file /nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023/sdevice.par
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023/sdevice1_des.cmd for node 38
'@tdr@' creates dependences with the node(s) '1'
+++Preprocessing results written to /nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023/pp38_des.cmd
The node '38' has dependencies to the node(s) '1'
---------------------------------------
Preprocessing file /nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023/sdevice.par for node 38
+++Preprocessing results written to /nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023/pp38_des.par
The node '38' has dependencies to the node(s) '1'
Start Simulation section
20:05:31 Nov 18 2023     job 38 <sdevice> started on host 'ug142': "sdevice --max_threads 2  pp38_des.cmd"
20:09:42 Nov 18 2023 +++ job 38 <sdevice> done: exit(0)
End Simulation section
Start Epilogue section
20:09:42 Nov 18 2023 *** job 38 pre/post execution: eval " gjob::find_extracted_vars "/nfs/ug/homes-1/h/hemarath/SentaurusDB/ECE335/ECE335_Project_1_2023/ECE335_Project_1_2023" n38_des.out 38 "
End Epilogue section
Job succeeded
gjob exits with status 0
